<?php

namespace Database\Seeders;

use App\Models\ExpenseCategory;
use Illuminate\Database\Seeder;

class ExpenseCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            ['name' => 'Salary', 'slug' => 'salary'],
            ['name' => 'Utility Bill', 'slug' => 'utility-bill'],
            ['name' => 'Maintenance', 'slug' => 'maintenance'],
            ['name' => 'Transport Cost', 'slug' => 'transport-cost'],
            ['name' => 'Scholarship', 'slug' => 'scholarship'],
            ['name' => 'Office Expense', 'slug' => 'office-expense'],

            ['name' => 'Wages', 'slug' => 'wages'],
            ['name' => 'Festival Bonus', 'slug' => 'festival-bonus'],
            ['name' => 'Special Bonus', 'slug' => 'special-bonus'],
            ['name' => 'Students Snacks & Other', 'slug' => 'students-snacks-other'],
            ['name' => 'Office Maintenance', 'slug' => 'office-maintenance'],
            ['name' => 'Office Expenses', 'slug' => 'office-expenses'],
            ['name' => 'Extra Care Salary', 'slug' => 'extra-care-salary'],
            ['name' => 'Others Honorium', 'slug' => 'others-honorium'],
            ['name' => 'School Book Cost', 'slug' => 'school-book-cost'],
            ['name' => 'School Events & Others', 'slug' => 'school-events-others'],
            ['name' => 'Arabic Department Books', 'slug' => 'arabic-department-books'],
            ['name' => 'Medicine', 'slug' => 'medicine'],
            ['name' => 'House Rent (Outside)', 'slug' => 'house-rent-outside'],
            ['name' => 'Entertainment Tiffin', 'slug' => 'entertainment-tiffin'],
            ['name' => 'Conveyance', 'slug' => 'conveyance'],
            ['name' => 'Entertainment Others', 'slug' => 'entertainment-others'],
            ['name' => 'Books', 'slug' => 'books'],
            ['name' => 'Copies', 'slug' => 'copies'],
            ['name' => 'Generator Fuel & Mobil', 'slug' => 'generator-fuel-mobil'],
            ['name' => 'Gas Stove & Cylinder', 'slug' => 'gas-stove-cylinder'],
            ['name' => 'Advertisement & Publicity', 'slug' => 'advertisement-publicity'],
            ['name' => 'Mobile Bill', 'slug' => 'mobile-bill'],
            ['name' => 'Office Stationery', 'slug' => 'office-stationery'],
            ['name' => 'Repairing & Maintenance', 'slug' => 'repairing-maintenance'],
            ['name' => 'Electric Bill', 'slug' => 'electric-bill'],
            ['name' => 'House Rent', 'slug' => 'house-rent'],
            ['name' => 'Books for Teachers', 'slug' => 'books-for-teachers'],
            ['name' => 'Ceremonial Expenses', 'slug' => 'ceremonial-expenses'],
            ['name' => 'Furniture Maintenance', 'slug' => 'furniture-maintenance'],
            ['name' => 'Electrical Maintenance', 'slug' => 'electrical-maintenance'],
            ['name' => 'Others Maintenance', 'slug' => 'others-maintenance'],
            ['name' => 'Vehicle / Auto Ricksha Maintenance', 'slug' => 'vehicle-auto-ricksha-maintenance'],
            ['name' => 'Cookeries & Cutleries', 'slug' => 'cookeries-cutleries'],
            ['name' => 'Gift & Donation', 'slug' => 'gift-donation'],
            ['name' => 'Teachers Training', 'slug' => 'teachers-training'],
            ['name' => 'School Classroom Decoration', 'slug' => 'school-classroom-decoration'],

            ['name' => 'News-Paper Bill', 'slug' => 'news-paper-bill'],
            ['name' => 'Parents & Teachers Meeting', 'slug' => 'parents-teachers-meeting'],
            ['name' => 'Annual Sports & Picnic Expenses', 'slug' => 'annual-sports-picnic-expenses'],
            ['name' => 'First Aid Box & Materials', 'slug' => 'first-aid-box-materials'],
            ['name' => 'Ablution Expenses', 'slug' => 'ablution-expenses'],
            ['name' => 'Internet Bill', 'slug' => 'internet-bill'],
            ['name' => 'Entertainment Lunch/Dinner', 'slug' => 'entertainment-lunch-dinner'],
            ['name' => 'Software Maintenance', 'slug' => 'software-maintenance'],
            ['name' => 'School Signboard', 'slug' => 'school-signboard'],
            ['name' => 'School Garden & Design', 'slug' => 'school-garden-design'],
            ['name' => 'Intersport Competition', 'slug' => 'intersport-competition'],
            ['name' => 'Debating Club', 'slug' => 'debating-club'],
            ['name' => 'Language Club', 'slug' => 'language-club'],
            ['name' => 'Recitation Competition', 'slug' => 'recitation-competition'],
            ['name' => 'Standard Bengali Pronunciation', 'slug' => 'standard-bengali-pronunciation'],
            ['name' => 'GCS Scholarship Expenses', 'slug' => 'gcs-scholarship-expenses'],
            ['name' => 'Home Visit Expenses', 'slug' => 'home-visit-expenses'],
            ['name' => 'School Canteen Expenses', 'slug' => 'school-canteen-expenses'],
            ['name' => 'School Cleanliness Management', 'slug' => 'school-cleanliness-management'],
            ['name' => 'Director Honorium', 'slug' => 'director-honorium'],
            ['name' => 'School Classroom Stationery', 'slug' => 'school-classroom-stationery'],
            ['name' => 'Mobile Set/Sim Accessories', 'slug' => 'mobile-set-sim-accessories'],
            ['name' => 'School Micro (Rent)', 'slug' => 'school-micro-rent'],
            ['name' => 'School Bag', 'slug' => 'school-bag'],
            ['name' => 'Others Expenses', 'slug' => 'others-expenses'],
            ['name' => 'Scholarship Expenses (Others)', 'slug' => 'scholarship-expenses-others'],
            ['name' => 'Science Club Equipments', 'slug' => 'science-club-equipments'],
            ['name' => 'Class Party Banner', 'slug' => 'class-party-banner'],
            ['name' => 'Annual Exam Result & Prize Distribution', 'slug' => 'annual-exam-result-prize-distribution'],
            ['name' => 'Uniform', 'slug' => 'uniform'],
            ['name' => 'Teachers Uniform', 'slug' => 'teachers-uniform'],
            ['name' => 'Admission Form', 'slug' => 'admission-form'],
            ['name' => 'AGM Expenses', 'slug' => 'agm-expenses'],
            ['name' => 'Annual Sports', 'slug' => 'annual-sports'],
            ['name' => 'Annual Sports - Dress', 'slug' => 'annual-sports-dress'],
            ['name' => 'Painting Expenses', 'slug' => 'painting-expenses'],
            ['name' => 'School Decoration', 'slug' => 'school-decoration'],
            ['name' => 'School Board', 'slug' => 'school-board'],
            ['name' => 'School Badge', 'slug' => 'school-badge'],
            ['name' => 'Annual Picnic', 'slug' => 'annual-picnic'],
            ['name' => 'Entertainment Tiffin (Hifz)', 'slug' => 'entertainment-tiffin-hifz'],
            ['name' => 'Entertainment Lunch (Hifz)', 'slug' => 'entertainment-lunch-hifz'],
            ['name' => 'Repair & Maintenance', 'slug' => 'repair-maintenance'],
            ['name' => 'School Academic Cost', 'slug' => 'school-academic-cost'],
            ['name' => 'School Tie', 'slug' => 'school-tie'],

            ['name' => 'Honourin (Hifz)', 'slug' => 'honourin-hifz'],
            ['name' => 'Painting Expenses (Hifz)', 'slug' => 'painting-expenses-hifz'],
            ['name' => 'Admission Fee Refund', 'slug' => 'admission-fee-refund'],
            ['name' => 'Furniture & Fixtures (Hifz)', 'slug' => 'furniture-fixtures-hifz'],
            ['name' => 'Hifz Department Banner', 'slug' => 'hifz-department-banner'],
            ['name' => 'School Decoration & Others', 'slug' => 'school-decoration-others'],
            ['name' => 'Office Decoration', 'slug' => 'office-decoration'],
            ['name' => 'School Dress (Clothes)', 'slug' => 'school-dress-clothes'],
            ['name' => 'Sanitary Goods',  'slug' => 'sanitary-goods'],
            ['name' => 'Asset Purchase',   'slug' => 'asset-purchase'],
        ];
        foreach ($categories as $category) {
            ExpenseCategory::firstOrCreate(['slug' => $category['slug']], [
                'name' => $category['name'],
            ]);
        }
    }
}
