<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\PermissionCategory;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $definitions = [
            ['name' => 'Dashboard',           'sort' => 1,  'permissions' => [
                ['name' => 'view_dashboard', 'display_name' => 'View Dashboard'],
                ['name' => 'view_todays_attendence', 'display_name' => 'View Attendace Card'],
                ['name' => 'view_fee_collection', 'display_name' => 'View Fee Collection Card'],
                ['name' => 'view_income_expense', 'display_name' => 'View Income Expense Card'],
                ['name' => 'view_asset', 'display_name' => 'View Total Asset'],
                ['name' => 'view_classwise_attendance', 'display_name' => 'View Classwise Attedance'],
                ['name' => 'view_recent_exam', 'display_name' => 'View Recent Exam'],
                ['name' => 'view_recent_notice', 'display_name' => 'View Recent Notices'],
            ]],
            ['name' => 'Academics',           'sort' => 2,  'permissions' => [
                ['name' => 'view_academics',              'display_name' => 'View Academics'],
                ['name' => 'manage_classes',              'display_name' => 'Manage Classes'],
                ['name' => 'manage_sections',             'display_name' => 'Manage Sections'],
                ['name' => 'manage_groups',               'display_name' => 'Manage Groups'],
                ['name' => 'manage_sessions',             'display_name' => 'Manage Academic Sessions'],
                ['name' => 'manage_subjects',             'display_name' => 'Manage Subjects'],
                ['name' => 'manage_classrooms',           'display_name' => 'Manage Classrooms'],
                ['name' => 'manage_routines',             'display_name' => 'Manage Class Routines'],
                ['name' => 'view_card_sessions',          'display_name' => 'View Sessions Card'],
                ['name' => 'view_card_classes',           'display_name' => 'View Classes Card'],
                ['name' => 'view_card_sections',          'display_name' => 'View Sections Card'],
                ['name' => 'view_card_groups',            'display_name' => 'View Groups Card'],
                ['name' => 'view_card_subjects',          'display_name' => 'View Subjects Card'],
                ['name' => 'view_card_class_rooms',       'display_name' => 'View Class Rooms Card'],
                ['name' => 'view_card_class_routine',     'display_name' => 'View Class Routine Card'],
            ]],
            ['name' => 'Attendance',          'sort' => 3,  'permissions' => [
                ['name' => 'view_attendance',             'display_name' => 'View Attendance'],
                ['name' => 'manage_attendance',           'display_name' => 'Manage Attendance'],
                ['name' => 'view_card_daily_attendance',  'display_name' => 'View Daily Attendance Card'],
                ['name' => 'view_card_monthly_attendance_report', 'display_name' => 'View Monthly Attendance Report Card'],
                ['name' => 'view_card_attendance_settings', 'display_name' => 'View Attendance Settings Card'],
            ]],
            ['name' => 'Students',            'sort' => 4,  'permissions' => [
                ['name' => 'view_students',               'display_name' => 'View Students'],
                ['name' => 'create_students',             'display_name' => 'Create Students'],
                ['name' => 'edit_students',               'display_name' => 'Edit Students'],
                ['name' => 'delete_students',             'display_name' => 'Delete Students'],
                ['name' => 'manage_teacher_section_assignments', 'display_name' => 'Manage Teacher Section Assignments'],
                ['name' => 'view_card_student_list',      'display_name' => 'View Student List Card'],
                ['name' => 'view_card_assign_teacher',    'display_name' => 'View Assign Teacher Card'],
                ['name' => 'view_card_generate_id_cards', 'display_name' => 'View Generate ID Cards Card'],
                ['name' => 'view_card_student_birthdays', 'display_name' => 'View Birthdays Card'],
                ['name' => 'view_card_new_admission',     'display_name' => 'View New Admission Card'],
                ['name' => 'view_card_promote_students',  'display_name' => 'View Promote Students Card'],
                ['name' => 'view_card_mid_year_correction', 'display_name' => 'View Mid-Year Correction Card'],
                ['name' => 'view_card_student_checkout',  'display_name' => 'View Student Checkout Card'],
                ['name' => 'view_card_academic_history',  'display_name' => 'View Academic History Card'],
                ['name' => 'view_card_student_certificates', 'display_name' => 'View Student Certificates Card'],
            ]],
            ['name' => 'Fee Collection',      'sort' => 5,  'permissions' => [
                ['name' => 'view_fees',                   'display_name' => 'View Fee Collection'],
                ['name' => 'manage_fee_categories',       'display_name' => 'Manage Fee Categories'],
                ['name' => 'manage_fee_sets',             'display_name' => 'Manage Fee Sets'],
                ['name' => 'manage_scholarships',         'display_name' => 'Manage Scholarships'],
                ['name' => 'manage_free_studentships',    'display_name' => 'Manage Free Studentships'],
                ['name' => 'manage_transports',           'display_name' => 'Manage Transports'],
                ['name' => 'manage_student_fees',         'display_name' => 'Manage Student Fees'],
                ['name' => 'collect_payments',            'display_name' => 'Collect Payments'],
                ['name' => 'view_payment_report',         'display_name' => 'View Payment Report'],
                ['name' => 'view_card_collect_payments',  'display_name' => 'View Collect Payments Card'],
                ['name' => 'view_card_fee_categories',    'display_name' => 'View Fee Categories Card'],
                ['name' => 'view_card_fee_sets',          'display_name' => 'View Fee Sets Card'],
                ['name' => 'view_card_scholarships',      'display_name' => 'View Scholarships Card'],
                ['name' => 'view_card_free_studentships', 'display_name' => 'View Free Studentships Card'],
                ['name' => 'view_card_transport_fees',    'display_name' => 'View Transport Fees Card'],
                ['name' => 'view_card_student_payment_report', 'display_name' => 'View Student Payment Report Card'],
                ['name' => 'view_card_student_receive_report', 'display_name' => 'View Student Receive Report Card'],
                ['name' => 'view_card_student_receivable_report', 'display_name' => 'View Student Receivable Report Card'],
                ['name' => 'view_card_classwise_due_report', 'display_name' => 'View Classwise Due Report Card'],
                ['name' => 'view_card_student_due_report', 'display_name' => 'View Student Due Report Card'],
                ['name' => 'view_card_discount_list',     'display_name' => 'View Discount List Card'],
            ]],
            ['name' => 'Financials',          'sort' => 6,  'permissions' => [
                ['name' => 'view_financials',             'display_name' => 'View Financials'],
                ['name' => 'manage_incomes',              'display_name' => 'Manage Incomes'],
                ['name' => 'manage_expenses',             'display_name' => 'Manage Expenses'],
                ['name' => 'manage_transactions',         'display_name' => 'Manage Transactions'],
                ['name' => 'manage_income_categories',    'display_name' => 'Manage Income Categories'],
                ['name' => 'manage_expense_categories',   'display_name' => 'Manage Expense Categories'],
                ['name' => 'manage_shareholder_transactions', 'display_name' => 'Manage Shareholder Transactions'],
                ['name' => 'view_card_incomes',           'display_name' => 'View Incomes Card'],
                ['name' => 'view_card_expenses',          'display_name' => 'View Expenses Card'],
                ['name' => 'view_card_capital',           'display_name' => 'View Capital Card'],
                ['name' => 'view_card_transactions',      'display_name' => 'View Transactions Card'],
                ['name' => 'view_card_income_categories', 'display_name' => 'View Income Categories Card'],
                ['name' => 'view_card_expense_categories','display_name' => 'View Expense Categories Card'],
            ]],
            ['name' => 'Result Management',   'sort' => 7,  'permissions' => [
                ['name' => 'view_results',                'display_name' => 'View Result Management'],
                ['name' => 'manage_exams',                'display_name' => 'Manage Exams'],
                ['name' => 'manage_student_subjects',     'display_name' => 'Manage Student Subjects'],
                ['name' => 'view_card_all_exams',         'display_name' => 'View All Exams Card'],
                ['name' => 'view_card_create_exam',       'display_name' => 'View Create Exam Card'],
                ['name' => 'view_card_subject_assignment','display_name' => 'View Subject Assignment Card'],
                ['name' => 'view_card_terminal_report',   'display_name' => 'View Terminal Report Card'],
                ['name' => 'view_card_tutorial_exam_report', 'display_name' => 'View Tutorial Exam Report Card'],
            ]],
            ['name' => 'Shareholders',        'sort' => 8,  'permissions' => [
                ['name' => 'view_shareholders',           'display_name' => 'View Shareholders'],
                ['name' => 'manage_shareholders',         'display_name' => 'Manage Shareholders'],
                ['name' => 'view_card_all_shareholders',  'display_name' => 'View All Shareholders Card'],
                ['name' => 'view_card_add_shareholder',   'display_name' => 'View Add Shareholder Card'],
            ]],
            ['name' => 'HR & Payroll',        'sort' => 9,  'permissions' => [
                ['name' => 'view_hr',                     'display_name' => 'View HR & Payroll'],
                ['name' => 'manage_employees',            'display_name' => 'Manage Employees'],
                ['name' => 'manage_designations',         'display_name' => 'Manage Designations'],
                ['name' => 'manage_departments',          'display_name' => 'Manage Departments'],
                ['name' => 'manage_salary_structures',    'display_name' => 'Manage Salary Structures'],
                ['name' => 'manage_payroll',              'display_name' => 'Manage Payroll'],
                ['name' => 'manage_leave_requests',       'display_name' => 'Manage Leave Requests'],
                ['name' => 'manage_payment_information',  'display_name' => 'Manage Payment Information'],
                ['name' => 'view_card_hr_dashboard',      'display_name' => 'View HR Dashboard Card'],
                ['name' => 'view_card_all_employees',     'display_name' => 'View All Employees Card'],
                ['name' => 'view_card_add_employee',      'display_name' => 'View Add Employee Card'],
                ['name' => 'view_card_departments',       'display_name' => 'View Departments Card'],
                ['name' => 'view_card_designations',      'display_name' => 'View Designations Card'],
                ['name' => 'view_card_salary_structures', 'display_name' => 'View Salary Structures Card'],
                ['name' => 'view_card_salary_defaults',   'display_name' => 'View Salary Defaults Card'],
                ['name' => 'view_card_payroll',           'display_name' => 'View Payroll Card'],
                ['name' => 'view_card_leave_requests',    'display_name' => 'View Leave Requests Card'],
                ['name' => 'view_card_leave_balances',    'display_name' => 'View Leave Balances Card'],
                ['name' => 'view_card_salary_sheet',      'display_name' => 'View Salary Sheet Card'],
                ['name' => 'view_card_payroll_summary',   'display_name' => 'View Payroll Summary Card'],
            ]],
            ['name' => 'Accounts',            'sort' => 10, 'permissions' => [
                ['name' => 'view_accounts',               'display_name' => 'View Accounts'],
                ['name' => 'manage_account_groups',       'display_name' => 'Manage Account Groups'],
                ['name' => 'manage_accounts_list',        'display_name' => 'Manage Accounts List'],
                ['name' => 'view_ledger',                 'display_name' => 'View Ledger'],
                ['name' => 'manage_accounting_periods',   'display_name' => 'Manage Accounting Periods'],
                ['name' => 'manage_journal_entries',      'display_name' => 'Manage Journal Entries'],
                ['name' => 'view_reports',                'display_name' => 'View Reports'],
                ['name' => 'manage_bank_accounts',        'display_name' => 'Manage Bank Accounts'],
                ['name' => 'manage_mobile_banking_accounts', 'display_name' => 'Manage Mobile Banking Accounts'],
                ['name' => 'manage_hand_cash',            'display_name' => 'Manage Hand Cash'],
                ['name' => 'view_card_ledger',            'display_name' => 'View Ledger Card'],
                ['name' => 'view_card_trial_balance',     'display_name' => 'View Trial Balance Card'],
                ['name' => 'view_card_detailed_trial_balance', 'display_name' => 'View Detailed Trial Balance Card'],
                ['name' => 'view_card_balance_sheet',     'display_name' => 'View Balance Sheet Card'],
                ['name' => 'view_card_cash_book',         'display_name' => 'View Cash Book Card'],
                ['name' => 'view_card_day_book',          'display_name' => 'View Day Book Card'],
                ['name' => 'view_card_income_expenditure','display_name' => 'View Income & Expenditure Card'],
                ['name' => 'view_card_cash_summary',      'display_name' => 'View Cash Summary Card'],
                ['name' => 'view_card_receipt_payment',   'display_name' => 'View Receipt & Payment Card'],
                ['name' => 'view_card_cash_flow',         'display_name' => 'View Cash Flow Card'],
                ['name' => 'view_card_bank_accounts',     'display_name' => 'View Bank Accounts Card'],
                ['name' => 'view_card_mobile_banking',    'display_name' => 'View Mobile Banking Card'],
                ['name' => 'view_card_hand_cash',         'display_name' => 'View Hand Cash Card'],
                ['name' => 'view_card_account_groups',    'display_name' => 'View Account Groups Card'],
                ['name' => 'view_card_chart_of_accounts', 'display_name' => 'View Chart of Accounts Card'],
                ['name' => 'view_card_accounting_periods','display_name' => 'View Accounting Periods Card'],
            ]],
            ['name' => 'Assets',              'sort' => 11, 'permissions' => [
                ['name' => 'view_assets',                 'display_name' => 'View Assets'],
                ['name' => 'manage_assets',               'display_name' => 'Manage Assets'],
                ['name' => 'manage_asset_categories',     'display_name' => 'Manage Asset Categories'],
                ['name' => 'manage_asset_purchases',      'display_name' => 'Manage Asset Purchases'],
                ['name' => 'manage_asset_issues',         'display_name' => 'Manage Asset Issues'],
                ['name' => 'view_card_asset_categories',  'display_name' => 'View Asset Categories Card'],
                ['name' => 'view_card_assets_list',       'display_name' => 'View Assets List Card'],
                ['name' => 'view_card_asset_purchases',   'display_name' => 'View Asset Purchases Card'],
                ['name' => 'view_card_asset_issue_register', 'display_name' => 'View Asset Issue Register Card'],
                ['name' => 'view_card_asset_stock',       'display_name' => 'View Asset Stock Card'],
                ['name' => 'view_card_facility_bookings', 'display_name' => 'View Facility Bookings Card'],
            ]],
            ['name' => 'Inventory',           'sort' => 12, 'permissions' => [
                ['name' => 'view_inventory',              'display_name' => 'View Inventory'],
                ['name' => 'manage_inventory_categories', 'display_name' => 'Manage Inventory Categories'],
                ['name' => 'manage_inventory_products',   'display_name' => 'Manage Inventory Products'],
                ['name' => 'manage_inventory_suppliers',  'display_name' => 'Manage Inventory Suppliers'],
                ['name' => 'manage_inventory_purchases',  'display_name' => 'Manage Inventory Purchases'],
                ['name' => 'view_inventory_reports',      'display_name' => 'View Inventory Reports'],
                ['name' => 'view_card_inventory_categories', 'display_name' => 'View Inventory Categories Card'],
                ['name' => 'view_card_inventory_products','display_name' => 'View Inventory Products Card'],
                ['name' => 'view_card_inventory_suppliers','display_name' => 'View Inventory Suppliers Card'],
                ['name' => 'view_card_inventory_purchases','display_name' => 'View Inventory Purchases Card'],
                ['name' => 'view_card_inventory_stock_report', 'display_name' => 'View Inventory Stock Report Card'],
                ['name' => 'view_card_inventory_low_stock','display_name' => 'View Inventory Low Stock Card'],
            ]],
            ['name' => 'Budget Control',      'sort' => 13, 'permissions' => [
                ['name' => 'view_budget',                 'display_name' => 'View Budget Control'],
                ['name' => 'manage_budget_allocations',   'display_name' => 'Manage Budget Allocations'],
                ['name' => 'view_card_budget_allocation', 'display_name' => 'View Budget Allocation Card'],
                ['name' => 'view_card_budget_vs_actual',  'display_name' => 'View Budget vs Actual Card'],
            ]],
            ['name' => 'Institute Settings',  'sort' => 14, 'permissions' => [
                ['name' => 'view_institute_settings',     'display_name' => 'View Institute Settings'],
                ['name' => 'manage_school_settings',      'display_name' => 'Manage School Settings'],
                ['name' => 'manage_id_card_templates',    'display_name' => 'Manage ID Card Templates'],
                ['name' => 'manage_buildings',            'display_name' => 'Manage Buildings'],
                ['name' => 'view_card_school_settings',   'display_name' => 'View School Settings Card'],
                ['name' => 'view_card_id_card_templates', 'display_name' => 'View ID Card Templates Card'],
                ['name' => 'view_card_buildings',         'display_name' => 'View Buildings Card'],
                ['name' => 'view_card_rooms',             'display_name' => 'View Rooms Card'],
            ]],
            ['name' => 'User & Roles',        'sort' => 15, 'permissions' => [
                ['name' => 'view_users',                  'display_name' => 'View Users'],
                ['name' => 'create_users',                'display_name' => 'Create Users'],
                ['name' => 'edit_users',                  'display_name' => 'Edit Users'],
                ['name' => 'delete_users',                'display_name' => 'Delete Users'],
                ['name' => 'view_roles',                  'display_name' => 'View Roles'],
                ['name' => 'create_roles',                'display_name' => 'Create Roles'],
                ['name' => 'edit_roles',                  'display_name' => 'Edit Roles'],
                ['name' => 'delete_roles',                'display_name' => 'Delete Roles'],
                ['name' => 'view_permissions',            'display_name' => 'View Permissions'],
                ['name' => 'edit_permissions',            'display_name' => 'Edit Permissions'],
                ['name' => 'view_card_users',             'display_name' => 'View Users Card'],
                ['name' => 'view_card_roles',             'display_name' => 'View Roles Card'],
                ['name' => 'view_card_permissions',       'display_name' => 'View Permissions Card'],
            ]],
            ['name' => 'Reports',             'sort' => 16, 'permissions' => [
                ['name' => 'view_reports_hub',            'display_name' => 'View Reports Hub'],
                ['name' => 'view_student_payment_report', 'display_name' => 'View Student Payment Report'],
                ['name' => 'view_card_reports_student_payment', 'display_name' => 'View Reports Student Payment Card'],
                ['name' => 'view_supplier_due_report',     'display_name' => 'View Supplier Due Report'],
            ]],
            ['name' => 'Location Settings',   'sort' => 17, 'permissions' => [
                ['name' => 'view_location_settings',      'display_name' => 'View Location Settings'],
                ['name' => 'manage_divisions',            'display_name' => 'Manage Divisions'],
                ['name' => 'manage_districts',            'display_name' => 'Manage Districts'],
                ['name' => 'manage_police_stations',      'display_name' => 'Manage Police Stations'],
                ['name' => 'manage_post_offices',         'display_name' => 'Manage Post Offices'],
                ['name' => 'view_card_divisions',         'display_name' => 'View Divisions Card'],
                ['name' => 'view_card_districts',         'display_name' => 'View Districts Card'],
                ['name' => 'view_card_police_stations',   'display_name' => 'View Police Stations Card'],
                ['name' => 'view_card_post_offices',      'display_name' => 'View Post Offices Card'],
            ]],
            ['name' => 'Website Management',  'sort' => 18, 'permissions' => [
                ['name' => 'view_website_management',     'display_name' => 'View Website Management'],
                ['name' => 'manage_website_content',      'display_name' => 'Manage Website Content'],
                ['name' => 'manage_academic_calendar',    'display_name' => 'Manage Academic Calendar'],
                ['name' => 'view_contact_messages',       'display_name' => 'View Contact Messages'],
            ]],
        ];

        foreach ($definitions as $group) {
            $categoryId = PermissionCategory::firstOrCreate(
                ['name' => $group['name']],
                ['sort_order' => $group['sort']]
            )->id;

            foreach ($group['permissions'] as $perm) {
                Permission::firstOrCreate(
                    ['name' => $perm['name']],
                    ['display_name' => $perm['display_name'], 'category_id' => $categoryId]
                );
            }
        }
    }
}
