@extends('layouts.master')

@section('contents')
@php
    $markedStudents = $passedStudents + $failedStudents;
    $passRate = $markedStudents > 0 ? round(($passedStudents / $markedStudents) * 100) : 0;
    $paymentRate = $totalApplications > 0 ? round(($paidApplications / $totalApplications) * 100) : 0;
    $admissionRate = $totalApplications > 0 ? round(($admittedStudents / $totalApplications) * 100) : 0;
@endphp
<div class="container-fluid py-4 admission-details-page">
    <div class="exam-hero mb-4">
        <div class="hero-content">
            <div class="d-flex flex-wrap align-items-center mb-2"><span class="hero-kicker"><i class="fas fa-chart-line mr-2"></i>Admission exam overview</span><span class="hero-status ml-sm-3 mt-2 mt-sm-0">{{ $exam->status ? 'Active exam' : 'Inactive exam' }}</span></div>
            <h1>{{ $exam->name }}</h1>
            <p class="hero-meta"><span><i class="far fa-calendar-alt mr-1"></i>{{ $exam->exam_date?->format('d M Y') }}</span><span><i class="fas fa-layer-group mr-1"></i>{{ $exam->academicSession?->name_en }}</span><span><i class="fas fa-wallet mr-1"></i>Form fee: ৳ {{ number_format((float) $exam->form_fee, 2) }}</span></p>
        </div>
        <div class="hero-actions"><a href="{{ route('admissions.exams') }}" class="btn btn-light mr-1"><i class="fas fa-arrow-left mr-1"></i>Exams</a><a href="{{ route('admissions.applications', ['exam_id' => $exam->id]) }}" class="btn btn-hero"><i class="fas fa-users mr-1"></i>Applications</a></div>
    </div>

    <div class="section-heading"><div><h3>Exam snapshot</h3><p>Track applicants from registration through admission.</p></div><span class="updated-label"><i class="fas fa-database mr-1"></i>Live data</span></div>
    <div class="row mb-4">
        @foreach([
            ['Total Applications', $totalApplications, 'fa-file-alt', 'blue', 'All submitted applications'], ['Student Appeared', $appearedStudents, 'fa-user-check', 'cyan', 'Marked present'], ['Passed', $passedStudents, 'fa-check-circle', 'green', 'Met the pass mark'], ['Failed', $failedStudents, 'fa-times-circle', 'red', 'Below the pass mark'], ['Admitted Student', $admittedStudents, 'fa-user-graduate', 'violet', 'Converted to student'], ['Not Admitted', $notAdmittedStudents, 'fa-user-clock', 'amber', 'Awaiting conversion'],
        ] as [$label, $value, $icon, $color, $caption])
            <div class="col-sm-6 col-xl-2 mb-3"><div class="metric-card metric-{{ $color }} h-100"><div class="metric-top"><span class="metric-icon"><i class="fas {{ $icon }}"></i></span><i class="fas fa-ellipsis-h metric-dots"></i></div><div class="metric-value">{{ $value }}</div><div class="metric-label">{{ $label }}</div><div class="metric-caption">{{ $caption }}</div></div></div>
        @endforeach
    </div>

    <div class="row mb-4">
        <div class="col-lg-8 mb-4 mb-lg-0"><div class="panel-card h-100"><div class="panel-heading"><div><h4>Admission funnel</h4><p>Key conversion rates for this examination.</p></div><i class="fas fa-filter panel-heading-icon"></i></div><div class="funnel-grid">
            <div class="funnel-item"><div class="funnel-line"><span>Payment completion</span><strong>{{ $paymentRate }}%</strong></div><div class="progress"><div class="progress-bar bg-info" style="width: {{ $paymentRate }}%"></div></div><small>{{ $paidApplications }} of {{ $totalApplications }} applications paid</small></div>
            <div class="funnel-item"><div class="funnel-line"><span>Pass rate</span><strong>{{ $passRate }}%</strong></div><div class="progress"><div class="progress-bar bg-success" style="width: {{ $passRate }}%"></div></div><small>{{ $passedStudents }} of {{ $markedStudents }} marked students passed</small></div>
            <div class="funnel-item"><div class="funnel-line"><span>Admission conversion</span><strong>{{ $admissionRate }}%</strong></div><div class="progress"><div class="progress-bar bg-primary" style="width: {{ $admissionRate }}%"></div></div><small>{{ $admittedStudents }} of {{ $totalApplications }} applications admitted</small></div>
        </div></div></div>
        <div class="col-lg-4"><div class="panel-card h-100"><div class="panel-heading"><div><h4>Pipeline summary</h4><p>Items needing attention.</p></div><i class="fas fa-clipboard-list panel-heading-icon"></i></div><div class="summary-list">
            <div><span><i class="fas fa-hourglass-half text-warning mr-2"></i>Pending review</span><strong>{{ $pendingReview }}</strong></div><div><span><i class="fas fa-user-check text-success mr-2"></i>Approved, not admitted</span><strong>{{ $approvedAwaitingAdmission }}</strong></div><div><span><i class="fas fa-user-times text-danger mr-2"></i>Rejected review</span><strong>{{ $rejectedApplications }}</strong></div><div><span><i class="fas fa-chart-bar text-primary mr-2"></i>Average marks</span><strong>{{ $averageMarks !== null ? number_format((float) $averageMarks, 2) : '-' }}</strong></div><div><span><i class="fas fa-coins text-success mr-2"></i>Payment collected</span><strong>৳ {{ number_format($collectedAmount, 2) }}</strong></div>
        </div></div></div>
    </div>

    <div class="panel-card"><div class="panel-heading"><div><h4>Classwise performance</h4><p>Compare application, attendance, result, and admission activity by class.</p></div><span class="table-count">{{ $classBreakdown->count() }} classes</span></div><div class="table-responsive"><table class="table performance-table mb-0"><thead><tr><th>Class</th><th>Applications</th><th>Paid</th><th>Appeared</th><th>Passed</th><th>Failed</th><th>Admitted</th></tr></thead><tbody>
        @forelse($classBreakdown as $row)<tr><td><span class="class-avatar">{{ strtoupper(substr($row['class'], 0, 1)) }}</span><strong>{{ $row['class'] }}</strong></td><td>{{ $row['total'] }}</td><td><span class="table-pill pill-blue">{{ $row['paid'] }}</span></td><td>{{ $row['appeared'] }}</td><td><span class="table-pill pill-green">{{ $row['passed'] }}</span></td><td><span class="table-pill pill-red">{{ $row['failed'] }}</span></td><td><span class="table-pill pill-violet">{{ $row['admitted'] }}</span></td></tr>@empty<tr><td colspan="7" class="text-center py-5 text-muted">No applications recorded for this exam.</td></tr>@endforelse
    </tbody></table></div></div>
</div>

<style>
    .admission-details-page { color: #172033; }.exam-hero { align-items: center; background: linear-gradient(118deg, #0b3b4a, #116b70 58%, #1599a1); border-radius: 16px; box-shadow: 0 12px 28px rgba(15, 91, 100, .18); color: #fff; display: flex; justify-content: space-between; min-height: 180px; overflow: hidden; padding: 30px 34px; position: relative; }.exam-hero:after { border: 1px solid rgba(255,255,255,.16); border-radius: 50%; content: ''; height: 280px; position: absolute; right: -80px; top: -150px; width: 280px; }.hero-content,.hero-actions { position: relative; z-index: 1; }.hero-kicker { color: #a7f3d0; font-size: 11px; font-weight: 700; letter-spacing: 1.3px; text-transform: uppercase; }.hero-status { background: rgba(255,255,255,.15); border: 1px solid rgba(255,255,255,.24); border-radius: 20px; font-size: 11px; padding: 5px 10px; }.exam-hero h1 { font-size: 30px; font-weight: 700; letter-spacing: -.5px; margin: 8px 0 10px; }.hero-meta { color: rgba(255,255,255,.78); font-size: 13px; margin: 0; }.hero-meta span { margin-right: 20px; }.btn-hero { background: #fff; color: #0b5962; font-weight: 600; }.btn-hero:hover { background: #e8fffa; color: #0b5962; }.section-heading { align-items: center; display: flex; justify-content: space-between; margin-bottom: 15px; }.section-heading h3 { font-size: 18px; margin: 0; }.section-heading p,.updated-label { color: #718096; font-size: 12px; margin: 4px 0 0; }.updated-label { background: #f0fdf4; border-radius: 20px; color: #16803c; padding: 7px 11px; }
    .metric-card { background: #fff; border: 1px solid #e8edf3; border-radius: 12px; box-shadow: 0 4px 12px rgba(30,41,59,.05); padding: 16px; position: relative; }.metric-top { align-items: center; display: flex; justify-content: space-between; }.metric-icon { align-items: center; border-radius: 9px; display: inline-flex; font-size: 14px; height: 32px; justify-content: center; width: 32px; }.metric-dots { color: #cbd5e1; font-size: 11px; }.metric-value { font-size: 26px; font-weight: 700; line-height: 1; margin-top: 16px; }.metric-label { color: #334155; font-size: 12px; font-weight: 600; margin-top: 7px; }.metric-caption { color: #94a3b8; font-size: 10px; margin-top: 3px; }.metric-blue .metric-icon { background:#eaf2ff;color:#2563eb; }.metric-cyan .metric-icon { background:#e6f9fb;color:#0891b2; }.metric-green .metric-icon { background:#eaf8ef;color:#16a34a; }.metric-red .metric-icon { background:#fff0f0;color:#dc2626; }.metric-violet .metric-icon { background:#f2edff;color:#7c3aed; }.metric-amber .metric-icon { background:#fff7e5;color:#d97706; }
    .panel-card { background: #fff; border: 1px solid #e8edf3; border-radius: 14px; box-shadow: 0 4px 12px rgba(30,41,59,.05); overflow: hidden; }.panel-heading { align-items: flex-start; border-bottom: 1px solid #edf1f5; display: flex; justify-content: space-between; padding: 17px 20px; }.panel-heading h4 { font-size: 15px; font-weight: 700; margin: 0; }.panel-heading p { color: #8492a6; font-size: 11px; margin: 4px 0 0; }.panel-heading-icon { color: #b7c4d3; font-size: 16px; }.funnel-grid { padding: 20px; }.funnel-item + .funnel-item { margin-top: 18px; }.funnel-line { display:flex; font-size: 12px; justify-content: space-between; margin-bottom: 7px; }.funnel-line strong { color:#0f766e; }.progress { background:#edf2f7; border-radius: 10px; height: 7px; }.progress-bar { border-radius: 10px; }.funnel-item small { color:#94a3b8; display:block; font-size:10px; margin-top:6px; }.summary-list { padding: 8px 20px 13px; }.summary-list > div { align-items:center; border-bottom: 1px solid #f0f3f6; display:flex; font-size:12px; justify-content:space-between; padding: 12px 0; }.summary-list > div:last-child { border-bottom:0; }.summary-list strong { font-size:13px; }.table-count { background:#f1f5f9; border-radius:20px; color:#64748b; font-size:10px; padding:6px 10px; }.performance-table thead th { background:#f8fafc; border-bottom:1px solid #e8edf3; color:#718096; font-size:10px; font-weight:700; letter-spacing:.3px; padding:12px 20px; text-transform:uppercase; white-space:nowrap; }.performance-table tbody td { border-top:1px solid #f0f3f6; color:#526174; font-size:12px; padding:13px 20px; vertical-align:middle; }.class-avatar { align-items:center; background:#e8f7f5; border-radius:8px; color:#0f766e; display:inline-flex; font-size:11px; font-weight:700; height:28px; justify-content:center; margin-right:9px; width:28px; }.table-pill { border-radius:12px; display:inline-block; font-size:11px; min-width:25px; padding:3px 7px; text-align:center; }.pill-blue { background:#eaf2ff;color:#2563eb; }.pill-green { background:#eaf8ef;color:#16803c; }.pill-red { background:#fff0f0;color:#dc2626; }.pill-violet { background:#f2edff;color:#7c3aed; }
    @media (max-width: 767.98px) { .exam-hero { align-items:flex-start; display:block; padding:24px; }.hero-actions { margin-top:22px; }.exam-hero h1 { font-size:24px; }.hero-meta span { display:block; margin:5px 0; }.section-heading { align-items:flex-start; display:block; }.updated-label { display:inline-block; margin-top:10px; } }
</style>
@endsection
