<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AdmitSeatCardSetting extends Model
{
    protected $fillable = [
        'card_type',
        'cards_per_page',
        'cards_per_row',
        'card_width_value',
        'card_height_value',
        'grid_gap_value',
        'card_dimension_unit',
        'card_front_alignment',
        'card_back_alignment',
        'card_front_padding_value',
        'card_back_padding_value',
        'card_photo_width_value',
        'card_photo_height_value',
        'card_logo_size_value',
        'card_school_name_font_size',
        'card_school_detail_font_size',
        'card_slogan_font_size',
        'card_title_font_size',
        'card_name_font_size',
        'card_name_text_color',
        'card_exam_type_font_size',
        'card_exam_name_font_size',
        'card_student_detail_alignment',
        'card_student_detail_font_size',
        'card_student_detail_text_color',
        'card_color_type',
        'card_color_gradient_1',
        'card_color_gradient_2',
        'card_solid_color',
        'card_logo',
        'card_is_transparent',
        'card_school_name_text_color',
        'card_school_detail_text_color',
        'card_slogan_text_color',
        'card_back_notice_text_color',
        'card_footer_text_color',
        'card_title_text_color',
        'card_exam_type_text_color',
        'card_exam_name_text_color',
        'card_show_logo_front',
        'card_show_logo_back',
        'card_show_photo_front',
        'card_show_footer_front',
        'card_show_footer_back',
        'card_show_school_detail_front',
        'card_show_school_detail_back',
        'card_show_slogan_front',
        'card_show_slogan_back',
        'card_show_title_front',
        'card_show_title_back',
        'card_show_exam_type_front',
        'card_show_exam_name_front',
        'card_show_back_notice',
    ];

    public static function current(int $cardType = 1): self
    {
        $cardType = in_array($cardType, [1, 2, 3, 4], true) ? $cardType : 1;
        $setting = static::firstOrNew(['card_type' => $cardType]);

        return $setting->fill([
            'card_is_transparent' => $setting->card_is_transparent ?? false,
            'card_color_type' => $setting->card_color_type ?? 'gradient',
            'card_front_alignment' => $setting->card_front_alignment ?? 'center',
            'card_back_alignment' => $setting->card_back_alignment ?? 'center',
            'card_front_padding_value' => $setting->card_front_padding_value ?? 0.8,
            'card_back_padding_value' => $setting->card_back_padding_value ?? 0.8,
            'card_photo_width_value' => $setting->card_photo_width_value ?? 1.8,
            'card_photo_height_value' => $setting->card_photo_height_value ?? 2.7,
            'card_logo_size_value' => $setting->card_logo_size_value ?? 0.8,
            'card_school_name_font_size' => $setting->card_school_name_font_size ?? 7.2,
            'card_school_detail_font_size' => $setting->card_school_detail_font_size ?? 5.4,
            'card_slogan_font_size' => $setting->card_slogan_font_size ?? 4.8,
            'card_title_font_size' => $setting->card_title_font_size ?? 4.7,
            'card_name_font_size' => $setting->card_name_font_size ?? 7.2,
            'card_name_text_color' => $setting->card_name_text_color ?? '#111827',
            'card_exam_type_font_size' => $setting->card_exam_type_font_size ?? 7.4,
            'card_exam_name_font_size' => $setting->card_exam_name_font_size ?? 6.8,
            'card_student_detail_alignment' => $setting->card_student_detail_alignment ?? 'left',
            'card_student_detail_font_size' => $setting->card_student_detail_font_size ?? 8.5,
            'card_student_detail_text_color' => $setting->card_student_detail_text_color ?? '#111827',
            'card_color_gradient_1' => $setting->card_color_gradient_1 ?? '#1e3a5f',
            'card_color_gradient_2' => $setting->card_color_gradient_2 ?? '#2563eb',
            'card_solid_color' => $setting->card_solid_color ?? '#1e3a5f',
            'card_school_name_text_color' => $setting->card_school_name_text_color ?? '#ffffff',
            'card_school_detail_text_color' => $setting->card_school_detail_text_color ?? '#e5e7eb',
            'card_slogan_text_color' => $setting->card_slogan_text_color ?? '#e5e7eb',
            'card_back_notice_text_color' => $setting->card_back_notice_text_color ?? '#94a3b8',
            'card_footer_text_color' => $setting->card_footer_text_color ?? '#e5e7eb',
            'card_title_text_color' => $setting->card_title_text_color ?? '#ffffff',
            'card_exam_type_text_color' => $setting->card_exam_type_text_color ?? '#ffffff',
            'card_exam_name_text_color' => $setting->card_exam_name_text_color ?? '#e5e7eb',
            'card_show_logo_front' => $setting->card_show_logo_front ?? true,
            'card_show_logo_back' => $setting->card_show_logo_back ?? true,
            'card_show_photo_front' => $setting->card_show_photo_front ?? true,
            'card_show_footer_front' => $setting->card_show_footer_front ?? true,
            'card_show_footer_back' => $setting->card_show_footer_back ?? true,
            'card_show_school_detail_front' => $setting->card_show_school_detail_front ?? true,
            'card_show_school_detail_back' => $setting->card_show_school_detail_back ?? true,
            'card_show_slogan_front' => $setting->card_show_slogan_front ?? true,
            'card_show_slogan_back' => $setting->card_show_slogan_back ?? true,
            'card_show_title_front' => $setting->card_show_title_front ?? true,
            'card_show_title_back' => $setting->card_show_title_back ?? true,
            'card_show_exam_type_front' => $setting->card_show_exam_type_front ?? true,
            'card_show_exam_name_front' => $setting->card_show_exam_name_front ?? true,
            'card_show_back_notice' => $setting->card_show_back_notice ?? true,
        ]);
    }
}
