<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProgressReportTemplateSetting extends Model
{
    protected $fillable = [
        'paper_orientation',
        'margin_top_mm',
        'margin_right_mm',
        'margin_bottom_mm',
        'margin_left_mm',
        'show_watermark',
        'watermark_opacity',
        'watermark_scale',
        'show_grade_scale',
        'show_student_info',
        'show_summary',
        'show_remarks',
        'show_comments',
        'show_signature',
        'show_print_date',
        'school_name_font_size',
        'school_address_font_size',
        'report_title_text',
        'report_title_font_size',
        'school_name_color',
        'school_address_color',
        'report_title_color',
        'header_border_color',
        'card_border_color',
        'table_header_bg_color',
        'table_header_text_color',
        'table_border_color',
        'table_row_alt_bg_color',
        'student_label_color',
        'student_value_color',
        'summary_bg_color',
        'summary_text_color',
        'remarks_title_color',
        'remarks_text_color',
        'signature_line_color',
        'remark_excellent_text',
        'remark_good_text',
        'remark_satisfactory_text',
        'remark_improve_text',
        'comments_excellent_text',
        'comments_good_text',
        'comments_default_text',
        'school_logo_max_width_mm',
        'subject_column_widths',
    ];

    protected $casts = [
        'show_watermark' => 'boolean',
        'show_grade_scale' => 'boolean',
        'show_student_info' => 'boolean',
        'show_summary' => 'boolean',
        'show_remarks' => 'boolean',
        'show_comments' => 'boolean',
        'show_signature' => 'boolean',
        'show_print_date' => 'boolean',
        'watermark_opacity' => 'float',
        'watermark_scale' => 'float',
        'margin_top_mm' => 'float',
        'margin_right_mm' => 'float',
        'margin_bottom_mm' => 'float',
        'margin_left_mm' => 'float',
        'school_name_font_size' => 'float',
        'school_address_font_size' => 'float',
        'report_title_font_size' => 'float',
        'school_logo_max_width_mm' => 'float',
        'subject_column_widths' => 'array',
    ];

    public static function current(): self
    {
        return static::firstOrNew(['id' => 1])->fill([
            'paper_orientation' => 'portrait',
            'margin_top_mm' => 8,
            'margin_right_mm' => 8,
            'margin_bottom_mm' => 8,
            'margin_left_mm' => 8,
            'show_watermark' => true,
            'watermark_opacity' => 0.08,
            'watermark_scale' => 78,
            'show_grade_scale' => true,
            'show_student_info' => true,
            'show_summary' => true,
            'show_remarks' => true,
            'show_comments' => true,
            'show_signature' => true,
            'show_print_date' => true,
            'school_name_font_size' => 16,
            'school_address_font_size' => 8.5,
            'report_title_text' => 'Progress Report',
            'report_title_font_size' => 17,
            'school_name_color' => '#5b8f42',
            'school_address_color' => '#5b8f42',
            'report_title_color' => '#d97706',
            'header_border_color' => '#111111',
            'card_border_color' => '#111111',
            'table_header_bg_color' => '#f3f4f6',
            'table_header_text_color' => '#111827',
            'table_border_color' => '#555555',
            'table_row_alt_bg_color' => '#f8fafc',
            'student_label_color' => '#111827',
            'student_value_color' => '#111827',
            'summary_bg_color' => '#111827',
            'summary_text_color' => '#ffffff',
            'remarks_title_color' => '#111827',
            'remarks_text_color' => '#374151',
            'signature_line_color' => '#111827',
            'remark_excellent_text' => 'Excellent',
            'remark_good_text' => 'Good',
            'remark_satisfactory_text' => 'Satisfactory',
            'remark_improve_text' => 'Need to be improved',
            'comments_excellent_text' => 'Excellent results! You faithfully perform classroom tasks.',
            'comments_good_text' => 'Good results! Keep up the good work.',
            'comments_default_text' => 'Need to improve performance.',
            'school_logo_max_width_mm' => 16,
            'subject_column_widths' => [
                'subject' => 30,
                'full_marks' => 10,
                'obtained_marks' => 12,
                'highest_marks' => 12,
                'total_marks' => 12,
                'letter_grade' => 12,
                'grade_point' => 12,
            ],
        ]);
    }
}
