<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class YearlyFinalReportTemplateSetting extends Model
{
    protected $fillable = [
        'paper_orientation',
        'margin_top_mm',
        'margin_right_mm',
        'margin_bottom_mm',
        'margin_left_mm',
        'show_watermark',
        'watermark_opacity',
        'watermark_scale',
        'show_grade_scale',
        'show_student_info',
        'show_table',
        'show_summary',
        'show_position',
        'show_remarks',
        'show_comments',
        'show_signature',
        'show_print_date',
        'school_name_font_size',
        'school_address_font_size',
        'report_title_text',
        'report_title_font_size',
        'annual_report_label',
        'school_name_color',
        'school_address_color',
        'report_title_color',
        'annual_report_color',
        'table_border_color',
        'table_header_bg_color',
        'table_header_text_color',
        'table_body_bg_color',
        'table_body_text_color',
        'grade_border_color',
        'position_border_color',
        'position_label_bg_color',
        'position_label_text_color',
        'position_value_text_color',
        'promo_box_bg_color',
        'promo_box_text_color',
        'remarks_title_color',
        'remarks_text_color',
        'remarks_note_color',
        'comments_border_color',
        'comments_text_color',
        'signature_line_color',
        'grade_scale_title',
        'pair_heading_1',
        'pair_heading_2',
        'pair_heading_3',
        'grand_total_label',
        'highest_total_label',
        'position_label_text',
        'promoted_text',
        'class_teacher_label',
        'principal_label',
        'remark_excellent_text',
        'remark_good_text',
        'remark_satisfactory_text',
        'remark_improve_text',
        'comments_excellent_text',
        'comments_good_text',
        'comments_default_text',
        'subject_column_widths',
    ];

    protected $casts = [
        'show_watermark' => 'boolean',
        'show_grade_scale' => 'boolean',
        'show_student_info' => 'boolean',
        'show_table' => 'boolean',
        'show_summary' => 'boolean',
        'show_position' => 'boolean',
        'show_remarks' => 'boolean',
        'show_comments' => 'boolean',
        'show_signature' => 'boolean',
        'show_print_date' => 'boolean',
        'watermark_opacity' => 'float',
        'watermark_scale' => 'float',
        'margin_top_mm' => 'float',
        'margin_right_mm' => 'float',
        'margin_bottom_mm' => 'float',
        'margin_left_mm' => 'float',
        'school_name_font_size' => 'float',
        'school_address_font_size' => 'float',
        'report_title_font_size' => 'float',
        'subject_column_widths' => 'array',
    ];

    public static function current(): self
    {
        $defaults = [
            'paper_orientation' => 'landscape',
            'margin_top_mm' => 8,
            'margin_right_mm' => 8,
            'margin_bottom_mm' => 8,
            'margin_left_mm' => 8,
            'show_watermark' => true,
            'watermark_opacity' => 0.14,
            'watermark_scale' => 96,
            'show_grade_scale' => true,
            'show_student_info' => true,
            'show_table' => true,
            'show_summary' => true,
            'show_position' => true,
            'show_remarks' => true,
            'show_comments' => true,
            'show_signature' => true,
            'show_print_date' => true,
            'school_name_font_size' => 24,
            'school_address_font_size' => 12,
            'report_title_text' => 'YEARLY FINAL RESULT',
            'report_title_font_size' => 22,
            'annual_report_label' => 'Annual Report',
            'school_name_color' => '#5b8f42',
            'school_address_color' => '#5b8f42',
            'report_title_color' => '#2f2f2f',
            'annual_report_color' => '#333333',
            'table_border_color' => '#7b7b7b',
            'table_header_bg_color' => '#f3f4f6',
            'table_header_text_color' => '#111827',
            'table_body_bg_color' => '#ffffff',
            'table_body_text_color' => '#222222',
            'grade_border_color' => '#7b7b7b',
            'position_border_color' => '#8ca06e',
            'position_label_bg_color' => '#9ccf63',
            'position_label_text_color' => '#1f3a1d',
            'position_value_text_color' => '#243524',
            'promo_box_bg_color' => '#7fbf3a',
            'promo_box_text_color' => '#17310e',
            'remarks_title_color' => '#444444',
            'remarks_text_color' => '#3f3f3f',
            'remarks_note_color' => '#1f4d1a',
            'comments_border_color' => '#a3a3a3',
            'comments_text_color' => '#333333',
            'signature_line_color' => '#111111',
            'grade_scale_title' => 'Letter Grade',
            'pair_heading_1' => '1st Terminal',
            'pair_heading_2' => '2nd Terminal',
            'pair_heading_3' => '3rd Terminal',
            'grand_total_label' => 'Grand Total',
            'highest_total_label' => 'Highest Marks',
            'position_label_text' => 'POSITION',
            'promoted_text' => 'Promoted',
            'class_teacher_label' => 'Class Teacher',
            'principal_label' => 'Principal',
            'remark_excellent_text' => 'Excellent',
            'remark_good_text' => 'Good',
            'remark_satisfactory_text' => 'Satisfactory',
            'remark_improve_text' => 'Need to be improved',
            'comments_excellent_text' => 'Excellent results! You faithfully perform classroom tasks.',
            'comments_good_text' => 'Good results! Keep up the good work.',
            'comments_default_text' => 'Need to improve performance.',
            'subject_column_widths' => [
                'pair1_tutorial' => 8,
                'pair1_terminal' => 8,
                'pair1_total' => 6,
                'pair1_weight' => 6,
                'pair2_tutorial' => 8,
                'pair2_terminal' => 8,
                'pair2_total' => 6,
                'pair2_weight' => 6,
                'pair3_tutorial' => 8,
                'pair3_terminal' => 8,
                'pair3_total' => 6,
                'pair3_weight' => 6,
                'grand_total' => 8,
                'highest' => 7,
            ],
        ];

        $setting = static::firstOrNew(['id' => 1]);

        return $setting->forceFill(array_merge($defaults, $setting->getAttributes()));
    }
}
